#!/bin/sh /etc/rc.common

START=21
STOP=89

USE_PROCD=1

FLAG_FILE="/tmp/dnsmasq_once"

msg() {
	logger -p daemon.info -st "clash[$$]" "$*"
}

start_service() {
	# The ruleset folder is used from tmpfs
	if [ ! -d /tmp/clash/ruleset ]; then
		mkdir -p /tmp/clash/ruleset
		msg "The folder '/tmp/clash/ruleset' was created"
	fi
	if [ ! -L /opt/clash/ruleset ] || [ "$(readlink /opt/clash/ruleset)" != "/tmp/clash/ruleset" ]; then
		rm -rf /opt/clash/ruleset
		ln -s /tmp/clash/ruleset /opt/clash/ruleset
		msg "Created a symlink from '/tmp/clash/ruleset' to '/opt/clash/ruleset'"
	fi
	
 	/opt/clash/bin/clash -d /opt/clash -t
	if [ $? -ne 0 ]; then
		msg "Clash instance is not started"
		return
	fi

	procd_open_instance
	procd_set_param command /opt/clash/bin/clash -d /opt/clash
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param respawn
	procd_close_instance
	msg "Clash instance is started"

	uci add_list dhcp.@dnsmasq[0].server='127.0.0.1#7874'
	uci set dhcp.@dnsmasq[0].cachesize='0'
	uci set dhcp.@dnsmasq[0].noresolv='1'
	uci commit dhcp
	msg "DNS settings have been changed"

	/opt/clash/bin/clash-rules start
	msg "Firewall rules applied"

	/etc/init.d/dnsmasq restart > /dev/null 2>&1
	msg "dnsmasq restarted"
}

stop_service() {
	msg "Clash instance has been stopped"
	uci del dhcp.@dnsmasq[0].server
	uci del dhcp.@dnsmasq[0].cachesize
	uci del dhcp.@dnsmasq[0].noresolv
	uci commit dhcp
	msg "DNS settings have been restored"

	/opt/clash/bin/clash-rules stop
	msg "Firewall rules have been restored"

	if [ ! -f "$FLAG_FILE" ]; then
		/etc/init.d/dnsmasq restart > /dev/null 2>&1
		msg "dnsmasq restarted"
	fi

	rm -f "$FLAG_FILE"
}

reload_service() {
	touch "$FLAG_FILE"
	stop
	start
}

boot() {
	sleep 10
	start
}
